### ISSUE TITLE
compile issure

### ISSUE THREAD

**Issue by ZhangXG-Git** [actions-security/pymodsecurity#1]
Hi all:
when I make the project,I meat an error,the issure as follow:
/home/test/modsecurity/pymodsecurity/src/action.cpp:2:40: fatal error: modsecurity/actions/action.h: No such file or directory
compilation terminated.

And I can't find this header file in the project.Please help.
Thanks!

**Comment by GustavoKatel** [comment]
Hi @ZhangXG-Git this header comes from ModSecurity itself. It's a known dependency. Can you confirm you have it installed? How are you compiling/installing the bindings?

**Comment by ZhangXG-Git** [comment]
> Hi @ZhangXG-Git this header comes from ModSecurity itself. It's a known dependency. Can you confirm you have it installed? How are you compiling/installing the bindings?
Hi @GustavoKatel:
I realized that I have not installed modsecurity yet.when I installed the modsecurity by default,the step are:
$ sh build.sh
$ git submodule init
$ git submodule update #[for bindings/python, others/libinjection, test/test-cases/secrules-language-tests]
$ ./configure
$ make
$ make install 
And I added
set(INCLUDES ${INCLUDES} /usr/local/modsecurity/include)
in the CMakeLists.txt.
But it still have some errors:
/home/test/modsecurity/pymodsecurity/src/collection.cpp:43:10: error: â€˜void pyCollection::resolveMultiMatches(const string&, std::vector<const modsecurity::VariableValue*>*)â€™ marked â€˜overrideâ€™, but does not override
     void resolveMultiMatches(const std::string& var, std::vector<const VariableValue *> *l) override {
          ^
/home/test/modsecurity/pymodsecurity/src/collection.cpp:47:10: error: â€˜void pyCollection::resolveRegularExpression(const string&, std::vector<const modsecurity::VariableValue*>*)â€™ marked â€˜overrideâ€™, but does not override
     void resolveRegularExpression(const std::string& var, std::vector<const VariableValue *> *l) override {
          ^
/home/test/modsecurity/pymodsecurity/src/collection.cpp:101:10: error: â€˜void pyCollection::resolveMultiMatches(const string&, std::__cxx11::string, std::vector<const modsecurity::VariableValue*>*)â€™ marked â€˜overrideâ€™, but does not override
     void resolveMultiMatches(const std::string& var, std::string compartment, std::vector<const VariableValue *> *l) override {
          ^
/home/test/modsecurity/pymodsecurity/src/collection.cpp:105:10: error: â€˜void pyCollection::resolveMultiMatches(const string&, std::__cxx11::string, std::__cxx11::string, std::vector<const modsecurity::VariableValue*>*)â€™ marked â€˜overrideâ€™, but does not override
     void resolveMultiMatches(const std::string& var, std::string compartment, std::string compartment2, std::vector<const VariableValue *> *l) override {
          ^
...
others,I install the pybind11 in the "/home/test/modsecurity/pymodsecurity/pybind11" directory,use python setup.py install.

I think the error may still be related to the installation dependencies, what should I do?
Thanks!

**Comment by GustavoKatel** [comment]
I see. Could you please share your compiler version and what distribution you are using? Also, could you check if installing the bindings from PyPi or via `python setup.py install` works?

**Comment by migolovanov** [comment]
I have the same issue on Ubuntu 18.04.
Compiler version is gcc-7, 7.3.0-27ubuntu1~18.04
Install from PyPi at first fails with error below and if fix this condition manually repeats the issue described
```
Traceback (most recent call last):
  File "setup.py", line 71, in <module>
    class BuildExt(build_ext):
  File "setup.py", line 87, in BuildExt
    raise RuntimeError('Platform is {} not supported'.format(sys.platform))
RuntimeError: Platform is linux2 not supported
```

**Comment by GustavoKatel** [comment]
Oh I see. Can you confirm which version of ModSecurity you both are using? It's fair to say and to add this to the README/docs that we only support the latest released version of ModSecurity, which you can download from the Releases tab of its Github: https://github.com/SpiderLabs/ModSecurity/releases

It looks like the overloads you are trying to compile with has changed since 3.0.2. We will improve our docs to note this out.

**Comment by ZhangXG-Git** [comment]
Hi @GustavoKatel：
I'm sorry for the late reply.
The gcc and distribution are that _gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10)_ 
The modsecurity code checkout from  v3 master.
When I used:python setup.py install,It still had some errors.

test@ubuntu:~/modsecurity/pymodsecurity$ sudo python setup.py install
[sudo] password for test: 
running install
running bdist_egg
running egg_info
writing dependency_links to pymodsecurity.egg-info/dependency_links.txt
writing pymodsecurity.egg-info/PKG-INFO
writing requirements to pymodsecurity.egg-info/requires.txt
writing top-level names to pymodsecurity.egg-info/top_level.txt
reading manifest file 'pymodsecurity.egg-info/SOURCES.txt'
writing manifest file 'pymodsecurity.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c /tmp/tmp1uer250r.cpp -o tmp/tmp1uer250r.o -std=c++14
cc1plus: warning: command line option â€˜-Wstrict-prototypesâ€™ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c /tmp/tmpfnfwfwt7.cpp -o tmp/tmpfnfwfwt7.o -fvisibility=hidden
cc1plus: warning: command line option â€˜-Wstrict-prototypesâ€™ is valid for C/ObjC but not for C++
building 'ModSecurity' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include/python3.5 -I/home/test/.local/include/python3.5m -I/usr/include/python3.5m -c src/variable_value.cpp -o build/temp.linux-x86_64-3.5/src/variable_value.o -lmodsecurity -DVERSION_INFO="0.0.2" -std=c++14 -fvisibility=hidden
cc1plus: warning: command line option â€˜-Wstrict-prototypesâ€™ is valid for C/ObjC but not for C++
**src/variable_value.cpp:2:40: fatal error: modsecurity/variable_value.h: No such file or directory**
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by GustavoKatel** [comment]
Hi @ZhangXG-Git no problem. You are using a not supported version of ModSecurity. The latest supported version is v3.0.2, which you can download from the releases page of their repo: https://github.com/SpiderLabs/ModSecurity/releases

Can you try compiling with the right version? and please let me know if you still see issues.

**Comment by migolovanov** [comment]
same here, was using master branch of ModSecurity, with 3.0.2 release compilation succeeded for python3.
However, for python2 besides issue with sys.platform saw the following error when installing via setup.py, so i guess it is just not supported.
```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/main.cpp:23:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(ModSecurity, m)
                ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
